### ISSUE TITLE
Find menu opens when typing punctuation in Opera

### ISSUE THREAD

**Issue by MrPerfectUver** [TheTypingMatch/community-feedback#9]
## Description
When typing a comma, period, or slash on the website in Opera, it opens the search page menu which takes your cursor away. As far as I know, these are default Opera shortcuts but they don't trigger on many other websites.

### How to Reproduce
1. Use Opera
2. Go to https://thetypingmatch.com
3. Start a test
4. Type one of the aforementioned punctuations
5. It opens the search menu and starts typing into that box

### Expected Behavior
The cursor should stay in the test and not open the search menu.

### Device
 - OS: MacOS
 - Browser: Opera Developer
 - Browser Version: 72.0.3807.0
 - Site Version: 0.2.1

**Comment by Ray-Adams** [comment]
## Simple & Quick Solution For Opera Users
1. Go to settings.
2. Search up "shortcuts" in the search bar.
3. Uncheck "advanced keyboard shortcuts".

**Comment by MrPerfectUver** [comment]
Already done and thank you!
